# Generated by Django 2.1.5 on 2020-06-08 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pooch_finder.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('negotiable', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('summary_desc', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=4000)),
                ('microchip_number', models.CharField(blank=True, max_length=200, null=True)),
                ('breeder_id', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_name', models.CharField(default='', max_length=64)),
                ('email', models.CharField(default='', max_length=64)),
                ('mobile', models.CharField(default='', max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Age_Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Dog_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=8)),
                ('suburb', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=5)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pooch_finder.models.photo_path_)),
                ('ad_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_item', to='pooch_finder.Ad_Item')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='ad_item',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ad_age', to='pooch_finder.Age_Cat'),
        ),
        migrations.AddField(
            model_name='ad_item',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ad_breed', to='pooch_finder.Breed'),
        ),
        migrations.AddField(
            model_name='ad_item',
            name='dog_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ad_type', to='pooch_finder.Dog_Type'),
        ),
        migrations.AddField(
            model_name='ad_item',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ad_gender', to='pooch_finder.Gender'),
        ),
        migrations.AddField(
            model_name='ad_item',
            name='item_location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ad_location', to='pooch_finder.Location'),
        ),
        migrations.AddField(
            model_name='ad_item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
