# Generated by Django 2.1.5 on 2020-06-11 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooch_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_item',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 1, 53, 41, 386102)),
        ),
    ]
